name: codex_frontend
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.6
  shared_preferences: ^2.0.15
  flutter_mjpeg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true